### ISSUE TITLE
Install fails if the registry key does not exist.

### ISSUE THREAD

**Issue by Zer0zzy** [midrare/hyperenable#10]
I ran into an issue where I did not have the `HKLM:\SOFTWARE\Classes\ms-officeapp\Shell\Open\Command` key in my registry, which caused the install to fail. This could be resolved by adding the -Force parameter in the New-Item command.

**Comment by nekowinston** [comment]
I ran into a similar issue, because `HKLM:\SOFTWARE\Classes\ms-officeapp\Shell\Open\Command` didn't exist, it worked once I created the parent keys:

```console
Writing HKLM:\SOFTWARE\Classes\ms-officeapp\Shell\Open\Command\rundll32
New-Item: C:\Users\winston\Downloads\hyperenable-v0.1.3\install.ps1:181
Line |
 181 |      New-Item -Path $MSOFFICE_REG_KEY -Value $MSOFFICE_REG_VALUE -Type …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The registry key at the specified path does not exist.
```

**Comment by midrare** [comment]
Fixed. Thanks for the report.
