### ISSUE TITLE
Can't get this to work whatsoever...

### ISSUE THREAD

**Issue by Dave3848** [midrare/hyperenable#12]
As displayed below, I cannot get the script to work... I've tried Googling vehemently in regards to ' The term './install.ps1' is not recognized as the name of a cmdlet...', but it's all super niche and specific... Could somebody, please help me?

![2024-03-02_13-48](https://github.com/midrare/hyperenable/assets/61253693/ddd8fb47-83ef-4899-b095-e8dd33657b0b)

**Comment by midrare** [comment]
You need to `cd` into the right folder. e.g. `cd c:/users/you/downloads/hyperenable-v0.1.3-2/` then run `./install`.

**Comment by Dave3848** [comment]
Oh, I see... Thank you!
