### ISSUE TITLE
Create an installer for automatic setup 

### ISSUE THREAD

**Issue by devnoname120** [midrare/hyperenable#4]
It looks like the install process is pretty straightforward and could be automated fairly easily.
What do you think?

**Comment by devnoname120** [comment]
A user-friendly alternative could be [NSIS](https://nsis.sourceforge.io/Screenshots): https://nsis.sourceforge.io/Simple_tutorials

**Comment by midrare** [comment]
I added a powershell script. Don't think NSIS is likely as I don't want to learn NSIS just for one project.
