### ISSUE TITLE
The README should mention the need to install C++ Build Tools

### ISSUE THREAD

**Issue by HereticHydra** [midrare/hyperenable#5]
The build instructions should probably mention that, when installing VS, you need to install the relevant C++ component highlighted below
![image](https://github.com/midrare/hyperenable/assets/68088455/b3aef89e-0485-4c61-81f4-d7b062734316)

or else you'll get errors about files (e.g., the 'cl' command below) not being found.
![image](https://github.com/midrare/hyperenable/assets/68088455/3b68d935-8a7c-4245-a85b-dca8a3315826)

**Comment by midrare** [comment]
Thanks for the report. Fixed.
