### ISSUE TITLE
hyperenable.exe triggers MS Defender

### ISSUE THREAD

**Issue by mpern** [midrare/hyperenable#8]
Hi!

first of all, thanks for the tool!

Unfortunately MS Defender detects `Trojan:Win32/Wacatac.B!ml` in hyperenable.exe v0.1.3

I guess you have to submit it for false positive detection?

https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by koitsu** [comment]
Assuming this is a false positive on the .exe, you can try compressing your binary with UPX and see if that gets around it.  I'm unsure if Defender can de-UPX things (I suspect it cannot).

**Comment by midrare** [comment]
I packed https://github.com/midrare/hyperenable/releases/tag/v0.1.3-2 with UPX. Could you give it a try and see if it still gets flagged?

**Comment by koitsu** [comment]
I myself have Defender completely disabled so I don't have an easy way to test it.  That said:

I uploaded the v0.1.3-2 UPX-packed .exe to Jotti's malware scan and it's clean: https://virusscan.jotti.org/en-GB/filescanjob/zp2rl5yugk

However, v0.1.3 was also clean, so definitely need to have someone test it with Defender: https://virusscan.jotti.org/en-GB/filescanjob/9mmdkhu3xy

**Comment by mpern** [comment]
so far, so good!
unpacking the latest release zip did not trigger Defender, I can also run `hyperenable --help` from the terminal.

**Comment by mpern** [comment]
after installing everything works as expected.
