### ISSUE TITLE
Return code 5 when running hyperenable from terminal

### ISSUE THREAD

**Issue by martin-braun** [midrare/hyperenable#9]
I added `hyperenable` to a path that is in my `$PATH`, when I launch it, it outputs nothing and the exit code is 5. I try to launch it with MSYS2's bash shell.

I also tried to supply its configuration, it doesn't work. I don't wish to install and auto start the tool, I want to launch it on demand.

Why is this not working please?

**Comment by midrare** [comment]
You have to install. hyperenable intercepts explorer.exe during startup. You can't intercept it after Windows is booted.

**Comment by martin-braun** [comment]
Why I have to install? I just killed `explorer.exe`, then I run `hyperenable start` and restarted `explorer.exe`:

```
Blocking keybinds.
Waiting for explorer.exe
Waiting until release signal or timeout.
Unblocking keybinds.
```

Is this the expected result? Before the office key website still opens when I press the hyper key combination ...

**Comment by midrare** [comment]
You start `hyperenable.exe` before `explorer.exe` starts, then kill it after `explorer.exe` is active. You could probably find a way to use hyperenable without installing, but it's not a use case that's officially supported.

**Comment by martin-braun** [comment]
@midrare Could you please elaborate? Although I get the expected result, the hotkey is still captured from `explorer.exe`

**Comment by midrare** [comment]
These should be the steps.

1. Kill `explorer.exe`
2. `hyperenable.exe start`
3. Start `explorer.exe`
4. Wait
5. `hyperenable.exe stop`

Did you try without config argument?

**Comment by martin-braun** [comment]
@midrare Thanks, I was missing `hyperenable.exe stop`:

<img width="644" alt="Screenshot 2024-01-27 at 20 59 05" src="https://github.com/midrare/hyperenable/assets/24259245/4f871ff8-320b-4a18-bbb9-747c54878e30">

The hotkey is still captured by `explorer.exe`. Same result when using the configuration.

It's ok mate, I already decided to kill `explorer.exe` for most of my workflow. This turned into a shtt OS. Windows 7 was the best, this is garbage. I just need to build some stuff on this OS for Windows users, so I kill `explorer.exe` and do everything in the shell and I'm in the process to get my configuration working with MSYS2 and then I just SSH onto Windows and still be able to use my shell tools. 

Screw M$, I refuse to waste more time with trying to get `explorer.exe` to behave my way, the OS is lost.
